# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofshift',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=9.33, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='bad_mix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='collapse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='dents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='mold_release',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='non_fill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='open_voilds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='over_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='tears',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='total_scrap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='trim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='under_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='voilds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='iso_pressure',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='poly_pressure',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(50)]),
        ),
    ]
