# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0002_auto_20170322_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapreport',
            name='contamination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='cracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='swollen',
            field=models.IntegerField(default=0),
        ),
    ]
