# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 04:28
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0002_timeoverrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overrides_enabled', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('shift', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('date', models.DateField(default=aspendb.models.get_today)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeOverrides',
        ),
    ]
