# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0002_auto_20170309_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofshift',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='downtime',
            unique_together=set([]),
        ),
    ]
