# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:02
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0003_auto_20170325_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborAllocationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[aspendb.models.date_validator])),
                ('shift', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('period', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Employee')),
                ('puller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puller', to='aspendb.Employee')),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooter', to='aspendb.Employee')),
                ('sprayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprayer', to='aspendb.Employee')),
                ('workcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell')),
            ],
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='adequate_iso',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='adequate_poly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='cabinet_stocked',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='pot_grounded',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='replacement_poly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='scrap_labeled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='spray_pots',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='adequate_components',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='airhose_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='chemical_tracked',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='new_product',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='opposite_parts',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='poly_agitator',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='process_verified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='stands_labels',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='weights_verified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='laborallocationreport',
            unique_together=set([('date', 'shift', 'workcell', 'period')]),
        ),
    ]
