# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0003_auto_20170309_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofshift',
            name='adequate_iso',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is there an adequate supply of iso?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='adequate_poly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is there an adequate supply of poly?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='cabinet_stocked',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Are all supplies in cell leader cabinet stocked?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='pot_grounded',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Is spray pot ground connected?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='replacement_poly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Is replacement poly agitating?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='scrap_labeled',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is all scrap properly labeled?'),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='spray_pots',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Is your spray pot topped off?'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='urgency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='part',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='workcell', chained_model_field='workcell', on_delete=django.db.models.deletion.CASCADE, to='aspendb.Part'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='adequate_components',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Is there an adequate supply of components?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='airhose_secure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Are all air hose nozzles secure?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='chemical_tracked',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3, verbose_name='Is poly/iso recorded in lot tracking book?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='new_product',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Are there any NEW production parts scheduled to run today?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='opposite_parts',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Are the NEW parts - symetrically opposite parts on the same turntable?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='poly_agitator',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Is poly agitator functioning?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='process_verified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Process parameters verified?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='stands_labels',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Are all pack stands/pack instructions & barcode labels in place?'),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='weights_verified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Shot weights verified?'),
        ),
    ]
