# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 01:29
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0003_auto_20170914_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborallocationreport',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='laborallocationreport',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='laborallocationreport',
            name='workcell',
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='numbers',
            field=models.TextField(blank=True, max_length=1000, validators=[aspendb.models.ScrapReport.scrap_numbers_validator]),
        ),
        migrations.DeleteModel(
            name='LaborAllocationReport',
        ),
    ]
