# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0004_auto_20170311_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default='1st', max_length=3),
            preserve_default=False,
        ),
    ]
