# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0004_auto_20170921_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workcell',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='workcell',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='plant', chained_model_field='plant', on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell'),
        ),
    ]
