# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0004_auto_20170325_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofshift',
            name='employee_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
