# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-22 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0005_auto_20170921_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endofshift',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laborreport',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeredprocessaudit',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processactivityreport',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotcheckreport',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startofshift',
            name='plant',
            field=models.CharField(default='manchester', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='workcell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell'),
        ),
    ]
