# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 05:34
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0005_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='date',
            field=models.DateField(validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='date',
            field=models.DateField(validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date',
            field=models.DateField(validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='date',
            field=models.DateField(validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='date',
            field=models.DateField(validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='workcell',
            name='cell_leader_1st',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_leader_1st', to='aspendb.Employee'),
        ),
        migrations.AlterField(
            model_name='workcell',
            name='cell_leader_2nd',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_leader_2nd', to='aspendb.Employee'),
        ),
        migrations.AlterField(
            model_name='workcell',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[aspendb.models.nospace_validator]),
        ),
    ]
