# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-12 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0006_auto_20170312_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcell',
            name='cell_leader_1st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_leader_1st', to='aspendb.Employee'),
        ),
        migrations.AlterField(
            model_name='workcell',
            name='cell_leader_2nd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell_leader_2nd', to='aspendb.Employee'),
        ),
    ]
