# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:28
from __future__ import unicode_literals

import aspendb.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0006_auto_20170325_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date(2017, 3, 26), validators=[aspendb.models.date_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='training_level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='employee_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of employees positioned here'),
        ),
    ]
