# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:40
from __future__ import unicode_literals

import aspendb.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0008_auto_20170328_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCheckReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[aspendb.models.date_validator])),
                ('shift', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('time', models.TimeField(auto_now=True)),
                ('qty_checked', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('defects', models.CharField(max_length=50)),
                ('packer_initials', models.CharField(max_length=3)),
                ('comments', models.TextField(max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Employee')),
                ('part', smart_selects.db_fields.ChainedForeignKey(chained_field='workcell', chained_model_field='workcell', on_delete=django.db.models.deletion.CASCADE, to='aspendb.Part')),
                ('workcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell')),
            ],
        ),
    ]
