# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:02
from __future__ import unicode_literals

import aspendb.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0009_auto_20170312_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[aspendb.models.date_validator], verbose_name='Date performed')),
                ('problem_code', models.CharField(choices=[('mech', 'Mechanical'), ('elec', 'Electrical'), ('pneu', 'Pneumatic'), ('hydr', 'Hydraulic'), ('water', 'Water'), ('struc', 'Structural'), ('chem', 'Chemical')], max_length=5)),
                ('work_done', models.CharField(blank=True, max_length=50)),
                ('repair_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('workcell_downtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parts_used', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('parts_reordered', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3)),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Employee', verbose_name='Work performed by')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[aspendb.models.date_validator])),
                ('shift', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('hours', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('shots', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_shots', models.IntegerField()),
                ('part', smart_selects.db_fields.ChainedForeignKey(chained_field='workcell', chained_model_field='workcell', on_delete=django.db.models.deletion.CASCADE, to='aspendb.Part')),
            ],
        ),
        migrations.AddField(
            model_name='workcell',
            name='turns_per_hour',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='workcell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspendb.MaintenanceRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='productionschedule',
            unique_together=set([('date', 'shift', 'workcell', 'part')]),
        ),
    ]
