# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0009_spotcheckreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotcheckreport',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
