# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0010_auto_20170315_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='workcell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='shots',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Shots per round'),
        ),
    ]
