# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:02
from __future__ import unicode_literals

import aspendb.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0010_auto_20170402_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='date',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='date_performed',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='spotcheckreport',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[aspendb.models.date_validator]),
        ),
    ]
