# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0011_auto_20170315_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=30),
        ),
    ]
