# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0012_auto_20170317_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapreport',
            name='dents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='mold_release',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='numbers',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapreport',
            name='total_scrap',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
