# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 08:54
from __future__ import unicode_literals

import aspendb.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0012_auto_20170405_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 427677, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 392769, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 410451, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 424012, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date_performed',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 434281, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 437190, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 402282, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 414848, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='spotcheckreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 430567, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 8, 54, 44, 405438, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
    ]
