# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:01
from __future__ import unicode_literals

import aspendb.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0013_auto_20170408_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 259404, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 231451, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 246153, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 256897, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date_performed',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 264012, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 266269, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 239773, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 249940, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='spotcheckreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 261409, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 9, 1, 44, 242260, tzinfo=utc), validators=[aspendb.models.date_validator]),
        ),
    ]
