# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0013_auto_20170317_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapreport',
            name='numbers',
            field=models.TextField(max_length=1000),
        ),
    ]
