# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:19
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0014_auto_20170408_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date_performed',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='spotcheckreport',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
        migrations.AlterField(
            model_name='startofshift',
            name='date',
            field=models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator]),
        ),
    ]
