# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:29
from __future__ import unicode_literals

import aspendb.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0015_auto_20170408_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessActivityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=aspendb.models.get_today, validators=[aspendb.models.date_validator])),
                ('shift', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=3)),
                ('defect', models.CharField(blank=True, max_length=20)),
                ('process_change', models.CharField(max_length=50)),
                ('effect', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('change_reverted', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Employee')),
                ('part', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='workcell', chained_model_field='workcell', null=True, on_delete=django.db.models.deletion.CASCADE, to='aspendb.Part')),
                ('workcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspendb.Workcell')),
            ],
        ),
    ]
