# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0019_layeredprocessaudit_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcell',
            name='table_time_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workcell',
            name='table_time_seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workcell',
            name='turns_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
