# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0020_auto_20170413_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='startofshift',
            name='starting_shot',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
