# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0022_auto_20170420_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofshift',
            name='starting_shot',
        ),
    ]
