# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0023_remove_endofshift_starting_shot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lpasafety',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='layeredprocessaudit',
            name='leader_safety',
        ),
        migrations.RemoveField(
            model_name='layeredprocessaudit',
            name='shooter_safety',
        ),
        migrations.RemoveField(
            model_name='layeredprocessaudit',
            name='table_safety',
        ),
        migrations.RemoveField(
            model_name='layeredprocessaudit',
            name='trim_safety',
        ),
        migrations.AddField(
            model_name='layeredprocessaudit',
            name='iso_exposure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeredprocessaudit',
            name='ppe',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeredprocessaudit',
            name='ppe_info',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layeredprocessaudit',
            name='sds',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LPASafety',
        ),
    ]
