# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0024_auto_20170420_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='representative_1st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_1st', to='aspendb.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='representative_2nd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_2nd', to='aspendb.Employee'),
        ),
    ]
