# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0027_auto_20170426_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborallocationreport',
            name='puller',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='shooter',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laborallocationreport',
            name='sprayer',
            field=models.CharField(max_length=30),
        ),
    ]
