# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0028_auto_20170427_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofshift',
            name='total_manhrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
