# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:30
from __future__ import unicode_literals

from django.db import migrations

def multiply_manhrs(apps, schema_editor):
    Eos = apps.get_model("aspendb", "EndOfShift")
    for eos in Eos.objects.all():
        eos.total_manhrs = eos.employee_count * 10
        eos.save()

class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0029_endofshift_total_manhrs'),
    ]

    operations = [
        migrations.RunPython(multiply_manhrs),
    ]
