# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0030_auto_20170427_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofshift',
            name='employee_count',
        ),
    ]
