# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0031_remove_endofshift_employee_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborreport',
            unique_together=set([]),
        ),
    ]
