# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 01:09
from __future__ import unicode_literals

import aspendb.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0032_auto_20170428_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofshift',
            name='labor_per_pc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endofshift',
            name='total_manhrs',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='scrapreport',
            name='numbers',
            field=models.TextField(max_length=1000, validators=[aspendb.models.ScrapReport.scrap_numbers_validator]),
        ),
    ]
