# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspendb', '0033_auto_20170625_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofshift',
            name='labor_per_pc',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
