# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def recalculate_labor_per_pc(apps, schema_editor):
        Eos = apps.get_model('aspendb', 'EndOfShift')
        for eos in Eos.objects.all():
            if eos.total_manhrs > 0:
                eos.save()

    dependencies = [
        ('aspendb', '0033_auto_20170625_2009'),
    ]

    operations = [
        migrations.RunPython(recalculate_labor_per_pc),
    ]
